# Use a Node.js base image
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy the package.json and package-lock.json (or yarn.lock) files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your frontend source code
COPY frontend/ .

# Expose the port the dev server runs on
EXPOSE 3001

# The command to start the development server is handled by docker-compose.yml
CMD ["npm", "start"]
