FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the backend files to the container
COPY backend/ .

# Install any backend dependencies
RUN pip install -r requirements.txt

# Expose the port on which your Flask app will run
EXPOSE 5001

# Start the Flask app
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "app:app"]
